% PCA_filenamesetup - T P McAuliffe 20/02/2020 for AstroEBSD v2

% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
% EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
% OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
% NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
% BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN 
% ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
% CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name=InputUser.HDF5_file(1:end-3);
name=strrep(name,',','p');
name=strrep(name,'.','p');

if PCA_Setup.PCA_EBSD==1 & PCA_Setup.PCA_EDX==1;
    PCA_Setup.suff='EBSD+EDS';
end
if PCA_Setup.PCA_EBSD==0 & PCA_Setup.PCA_EDX==1;
    PCA_Setup.suff='EDS';
end
if PCA_Setup.PCA_EBSD==1 & PCA_Setup.PCA_EDX==0;
    PCA_Setup.suff='EBSD';
end

InputUser.EBSD_File = InputUser.HDF5_file;
InputUser.BCF_folder=InputUser.HDF5_folder;
InputUser.name=name;

clear name
